### ISSUE TITLE
How to make a child block in the Calendar Event Format option?

### ISSUE THREAD

**Issue by ViTuDia** [dvargas92495/roamjs-google#1]
How to make a child block in the Calendar Event Format option?

<img width="646" alt="Screenshot 2022-11-21 at 09 41 04" src="https://user-images.githubusercontent.com/59163092/203004776-042524f4-7dbb-4de6-8942-f105f72c5442.png">

**Comment by dvargasfuertes** [comment]
Specify your format as a block tree elsewhere in your graph. Then copy and paste the block reference here. Updating the docs now to make this clearer

**Comment by ViTuDia** [comment]
Thanks 🙏
