### ISSUE TITLE
Cannot uploading files larger than ~250KB

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roamjs-google#13]
Initial report via email:

> Uploading a video does not work, the video is in mp4 format. I have also tried it with other videos and get the same 

Steps to reproduce.
1. upload file larger than 259KB

Response

```
body: ReadableStream
bodyUsed: false
headers: Headers {}
ok: false
redirected: false
status: 308
statusText: ""
type: "cors"
url: https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&access_token={someToken}&upload_id={someId}&access_token={someToken}
```

**Comment by dvargasfuertes** [comment]
have you uploaded an _image_ that's > 250KB? we expected to account for file size

**Comment by mdroidian** [comment]
I tried an image larger than 250kb and was unsuccessful.

**Comment by mdroidian** [comment]
Update on where I'm at:

I've found that

`handeFetch` receives the response with `r.status = 308` but also `r.ok = false` so it is returning Promise.reject

https://github.com/RoamJS/roamjs-components/blob/c5a0a30a81f28434f0e9b2eb1ca1986eb6d245b8/src/util/handleFetch.ts#L38-L46

```javascript
).then((r) => {
    if (!r.ok) {
      return r.text().then((e) => {
        try {
          return Promise.reject(JSON.parse(e));
        } catch {
          return Promise.reject(new Error(e));
        }
      });
```

so this isn't getting called:

https://github.com/RoamJS/google/blob/25a1db52067e1ebab395c441b9992cc90cbe4140/src/services/drive.ts#L125-L137

Just to test to see what happened, if I removed the `if (!r.ok) {` from `handleFetch`, Lines 125 to 137 in `drive` get called, but it's a endless loop.  Upon inspecting the headers, `contentRange` is being updated, but the response is still sending back `range:"bytes=0-262143"` each time.

**Comment by mdroidian** [comment]
#15
