### ISSUE TITLE
How to not get a link of the {summary}?

### ISSUE THREAD

**Issue by ViTuDia** [dvargas92495/roamjs-google#2]
What to fill in in the option box Calandar Event Format to not get the 
{summary} as a link after importing form Calendar?

<img width="646" alt="Screenshot 2022-11-21 at 09 41 04" src="https://user-images.githubusercontent.com/59163092/203005391-82953eb6-61e4-4352-aa54-98a2362b6e16.png">

**Comment by dvargasfuertes** [comment]
I had meant to disassociate the two earlier. Change is now under Roam Depot Review

**Comment by ViTuDia** [comment]
Thanks 🙏

**Comment by ViTuDia** [comment]
works now in version 2 in Roam, thanks
