### ISSUE TITLE
Failed to upload to google drive

### ISSUE THREAD

**Issue by Bencharbit** [dvargas92495/roamjs-google#4]
Hello Davi,d

Any idea what triggers this erro?
- Failed to upload file to google drive. Email support@roamjs.com with the error below:
    - {}

Thanks!

**Comment by dvargasfuertes** [comment]
Known issue with a fix that is under Roam Depot review

**Comment by Bencharbit** [comment]
Thanks a lot. Any way to track when the fix will be greenlighted and pushed? thanks!

**Comment by dvargasfuertes** [comment]
agh it looks like it was never originally posted for review when I deployed the fix 3 weeks ago - here's the review pr: https://github.com/Roam-Research/roam-depot/pull/425#issuecomment-1367484478

**Comment by oxddr** [comment]
I've just downloaded and started using the extension and I am getting the same error: 

```
- Failed to upload file to google drive. Email support@roamjs.com with the error below:
    - {}
```

Do you have any ideas what to do about it?
