### ISSUE TITLE
Trouble logging in

### ISSUE THREAD

**Issue by joshkal** [dvargas92495/roamjs-google#6]
I just installed the google extension on roam depot. When I try to log in, I just get a spinning bar. Using Safari.

<img width="654" alt="Screenshot 2023-03-15 at 7 07 56 PM" src="https://user-images.githubusercontent.com/59401554/225492806-e25fb8eb-ffc7-41b3-b81c-58cdacbce98a.png">

Thanks for all you're doing for the Roam community David!!

**Comment by dvargasfuertes** [comment]
Do you see this same issue on the desktop app?
