### ISSUE TITLE
Calendar Event Format: description

### ISSUE THREAD

**Issue by ViTuDia** [dvargas92495/roamjs-google#7]
IS it possible to have another Calendar Event Format added? Would like to use the note section of an event, I guess Google calls is "description".  

Is that possible to have integrated?

Thanks!

https://developers.google.com/calendar/api/v3/reference/events

**Comment by ViTuDia** [comment]
Thanks!

how does it work, Roam updated but cannot get it to work. Thanks!

**Comment by dvargasfuertes** [comment]
Roam still needs to approve the change before it's live
